# Cloudformation that runs once. Base is needed for AWS env. 

AWSTemplateFormatVersion: 2010-09-09
Description: '---'
# Metadata: 


Parameters:
  Email:
    Type: String
    Default: {{resolve:ssm:bf-cell-number}}
    Description: Your email address to receive alarms per email
    NoEcho: true
  Phone:
    Type: String
    Default: {{resolve:ssm:bf-cell-number}}
    Description: Your mobile phone number to receive SMS
    NoEcho: true

Mappings:
  EstimatedCharges:
    AlarmRange:
      One: 20 # It will trigger an alarm if your billing gets higher than $20
      Two: 50 # It will trigger an alarm if your billing gets higher than $50
      Three: 100 # It will trigger an alarm if your billing gets higher than $100
      Four: 500 # It will trigger an alarm if your billing gets higher than $500
      Five: 1000 # It will trigger an alarm if your billing gets higher than $1000

# Conditions: 

Resources:
  General:
    # Don't name resources. Create the prefix needed. 
    # Pascal/title case. 
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: name
          Value: general

  BillingAlertOne:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref BillingAlertTopic
      AlarmDescription: !Join
        - ''
        - - Billing Alert for $
          - !FindInMap
            - EstimatedCharges
            - AlarmRange
            - One
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Currency
          Value: USD
      EvaluationPeriods: 1
      MetricName: EstimatedCharges
      Namespace: AWS/Billing
      Period: 21600
      TreatMissingData: breaching
      Statistic: Maximum
      Threshold: !FindInMap
        - EstimatedCharges
        - AlarmRange
        - One

  BillingAlertTopic:
    Type: AWS::SNS::Topic

  AlarmSubscriberEmail:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref Email
      Protocol: email
      TopicArn: !Ref BillingAlertTopic

  AlarmSubscriberSMS:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref Phone
      Protocol: sms
      TopicArn: !Ref BillingAlertTopic

Outputs:
  GeneralBucketName:
    Description: Description for general bucket
    Value: !Ref General
    Export:
      Name: !Sub ${AWS::StackName}-GeneralBucketName