# Cloudformation that runs once. Base is needed for AWS env. 

AWSTemplateFormatVersion: 2010-09-09
Description: '---'

Parameters:
  BranchName:
    Type: String
    Description: The name of the GitHub branch used to create this stack. To be overriden in deploy function. 
    Default: dev
  
  EnvironmentType:
    Type: String
    Description: "The environment type for which this is being deployed into."
    Default: dev
    AllowedValues:
      - dev
      - prod
      - stage
    ConstraintDescription: "Must be dev, prod, or stage."

Resources:
  General:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: name
          Value: general

Outputs:
  GeneralBucketName:
    Description: Description for general bucket
    Value: !Ref General
    Export:
      Name: !Sub ${AWS::StackName}-GeneralBucketName