AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template with a simple API definition

Parameters:
  BranchName:
    Type: String
    Description: The name of the GitHub branch used to create this stack. To be overriden in deploy function. 
    Default: dev
  
  EnvironmentType:
    Type: String
    Description: "The environment type for which this is being deployed into."
    Default: dev
    AllowedValues:
      - dev
      - prod
      - stage
    ConstraintDescription: "Must be dev, prod, or stage."

Resources:

  ApiGatewayApi:
  # This creates the rest API and sets the name of the stage to the Environment Type
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref EnvironmentType
  
  # Adds a GET method at the root resource via an Api event
  ApiFunction: 
    Type: AWS::Serverless::Function
    Properties:
      Events:
        Root:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId: !Ref ApiGatewayApi

        RootProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref ApiGatewayApi

      Role: !GetAtt ListTrackerIAMExecutionRole.Arn
      Runtime: python3.10
      Handler: index.handler
      CodeUri: ../api/ 
      LoggingConfig:
        LogGroup: !Ref ApiRootLogs

  ApiRootLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 1
      
  ListTrackerIAMExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service: 
             - lambda.amazonaws.com
             - apigateway.amazonaws.com
          Action: 'sts:AssumeRole'
      Policies:
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: '*'
              # TODO: Specify the exact resource later. 
              Resource: '*'
            - Effect: Allow
              Action: '*'
              Resource: 
                - !GetAtt ApiRootLogs.Arn
                - !Join [ "", [ !GetAtt ApiRootLogs.Arn, "/*" ] ]
