AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template with a simple API definition

Parameters:
  BranchName:
    Type: String
    Description: The name of the GitHub branch used to create this stack. To be overriden in deploy function. 
    Default: dev

Resources:
  
  # setup deletion protection on prod, use mapping
  ListTrackerDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      DeletionProtectionEnabled: false
      TableName: !Sub "${AWS::StackName}-lists"
      AttributeDefinitions:
        - 
          AttributeName: "user_id"
          AttributeType: "S"
        -
          AttributeName: "list_id"
          AttributeType: "S"
      KeySchema:
        - 
          AttributeName: "user_id"
          KeyType: "HASH"   # Partition Key
        - 
          AttributeName: "list_id"
          KeyType: "RANGE"   # Sort Key

      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      
      Tags:
        - Key: name
          Value: dyanmodbtable 

Outputs:
  ListTrackerDynamoDBTableARN:
     Value: !GetAtt ListTrackerDynamoDBTable.Arn
     Export:
        Name: ListTrackerDynamoDBTableARN