name: Deploy Python Lambda API

on: 
  workflow_dispatch:
  pull_request:


env:
  AWS_REGION : us-east-1 # Change to reflect your Region

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkou


jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ASSUME_ACTION_ROLE_ACCT_ID }}:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2 # To fetch the current commit and its parent (so we can compare)

    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ secrets.ASSUME_ACTION_ROLE_ACCT_ID }}:role/GitHubAction-AssumeRoleWithAction #change to reflect your IAM role’s ARN
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ env.AWS_REGION }}

    - name: Print changed files # To properly debug what is being deployed (It can be removed).
      run: |
        echo "List of changed files:" 
        echo $(git diff --name-only HEAD^ HEAD)

    - name: Deploy Modified Files
      run: |
        aws cloudformation deploy \
            --template-file cloudformations/00_foundation.yaml \
            --stack-name foundation \
            --tags name=foundation

        # Getting the GeneralBucketName 

        GeneralBucketName=$(aws cloudformation describe-stacks \
            --stack-name foundation \
            --query 'Stacks[0].Outputs[?OutputKey==`GeneralBucketName`].OutputValue' \
            --output text)

        # Deploying the API

        cfndir=$PWD
        cd api
        pip install -r requirements.txt -t .
        cd $cfndir


        aws cloudformation package \
            --template-file cloudformations/01_api.yaml \
            --s3-bucket $GeneralBucketName \
            --s3-prefix infrastructure/api \
            --output-template-file cloudformations/01_api_generated.yaml \


        # TODO: Upload to bucket. 

        aws cloudformation deploy \
            --template-file cloudformations/01_api_generated.yaml \
            --stack-name listtracker-api-${{ github.head_ref }} \
            --capabilities CAPABILITY_IAM \
            --capabilities CAPABILITY_NAMED_IAM


# create dyanmic name fo rhte cloudformation here, set it ot the branch name. 