name: CloudFormation Validation

on: 
  workflow_dispatch:
  pull_request:


jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

        # Set the naems of the files to check in the "cfn-lint" command area. 

      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint --version
          cfn-lint cloudformations/*.yaml