name: CloudFormation Validation

on: 
  workflow_dispatch:
  pull_request:


jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint --version
          cfn-lint cloudformations/*.yaml

      - name: Echo branch name
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "Branch Name: ${{ github.head_ref }}"
          else
            echo "Branch Name: ${GITHUB_REF#refs/heads/}"
          fi
        